# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_cakes_custom_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdimension',
            name='name_of_shape',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
