# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20171108_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicingredient',
            name='name_of_classic_ingredient',
        ),
        migrations.AddField(
            model_name='classicingredient',
            name='name_of_ingredient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
