# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20171108_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='other',
        ),
        migrations.AddField(
            model_name='cake',
            name='other',
            field=models.ManyToManyField(to='themes.OtherIngredient'),
        ),
    ]
