# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_auto_20171108_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherIngredient',
            new_name='NutIngredients',
        ),
        migrations.AlterModelOptions(
            name='nutingredients',
            options={'verbose_name': 'Nuts Ingredient', 'verbose_name_plural': 'Nuts Ingredients'},
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='other',
            new_name='nut_ingredients',
        ),
        migrations.RenameField(
            model_name='nutingredients',
            old_name='name_of_other_ingredient',
            new_name='name_of_nut_ingredient',
        ),
    ]
