# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0011_auto_20171108_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='classic_ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='themes.ClassicIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='custom_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.CustomDimension'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='fruit_ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='themes.FruitIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='nut_ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='themes.NutIngredients'),
        ),
    ]
