# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0012_auto_20171108_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='classic_ingredient',
            field=models.ManyToManyField(blank=True, to='themes.ClassicIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='fruit_ingredient',
            field=models.ManyToManyField(blank=True, to='themes.FruitIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='nut_ingredients',
            field=models.ManyToManyField(blank=True, to='themes.NutIngredients'),
        ),
    ]
