# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0013_auto_20171108_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='size',
        ),
        migrations.AlterField(
            model_name='cake',
            name='classic_ingredient',
            field=models.ManyToManyField(blank=True, related_name='classic_ingredient', to='themes.ClassicIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='custom_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dimension', to='themes.CustomDimension'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='dimension',
            field=models.ManyToManyField(related_name='dimensions', to='themes.Dimension'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='fruit_ingredient',
            field=models.ManyToManyField(blank=True, related_name='fruit_ingredient', to='themes.FruitIngredient'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='nut_ingredients',
            field=models.ManyToManyField(blank=True, related_name='nut_ingredients', to='themes.NutIngredients'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='toppings',
            field=models.ManyToManyField(related_name='topping', to='themes.Topping'),
        ),
    ]
