# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0014_auto_20171117_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cake_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
