# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0015_cake_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cake_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
