# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20171122_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
