# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_userprofile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
